// Code generated by "stringer -type=TestEnum"; DO NOT EDIT.

package testcons

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[string1-0]
	_ = x[string2-1]
}

const _TestEnum_name = "string1string2"

var _TestEnum_index = [...]uint8{0, 7, 14}

func (i TestEnum) String() string {
	if i < 0 || i >= TestEnum(len(_TestEnum_index)-1) {
		return "TestEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestEnum_name[_TestEnum_index[i]:_TestEnum_index[i+1]]
}
