// testenum_enummethods.go is auto generated by utility enummethods. DO NOT EDIT
// This file have some type methods implementing the Enumerator and json.Marshaler, json.Unmarshaler interfaces.
package testcons

import (
	"strings"

	"sourcecraft.dev/ivi-ippolitov/enummethods/enumerator"
)

// IsValid проверка корректности значения
// Реализует интерфейс Validator
func (m TestEnum) IsValid() bool {
	switch m {
	case string1, string2:
		return true
	}
	return false
}

// MarshalJSON - реализует метод интерфейса json.Marshaler
func (m TestEnum) MarshalJSON() ([]byte, error) {
	return enumerator.MarshalJSON(m)
}

// UnmarshalJSON - реализует метод интерфейса json.UnMarshaler
func (m *TestEnum) UnmarshalJSON(data []byte) error {
	return enumerator.UnmarshalJSON(m, data)
}

// MarshalYAML - реализует метод интерфейса yaml.Marshaler
func (m TestEnum) MarshalYAML() (interface{}, error) {
	return enumerator.MarshalYAML(m)
}

// UnmarshalYAML - реализует метод интерфейса yaml.UnMarshaler
func (m *TestEnum) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return enumerator.UnmarshalYAML(m, unmarshal)
}

// SetValue конвертация строки в значение типа
// Реализует интерфейс Unstringer
func (m *TestEnum) SetValue(s string) bool {
	i := strings.Index(_TestEnum_name, s)
	if i != -1 {
		for index, v := range _TestEnum_index {
			if i-int(v) == 0 {
				*m = TestEnum(index)
				return true
			}
		}
	}
	return false
}
